
server:
  port: 20082
spring:
  application:
    name: client
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20080/eureka/
    fetch-registry: true