server:
  port: 20086
spring:
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/studyouou/SpringcloudConfig
      enabled: true
      discovery:
        service-id: config-client1
        enabled: true
  application:
    name: config-client1
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:20080/eureka
